import ConfigureAmplifyClientSide from "../../config/amplify-cognito-config"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <>
          <ConfigureAmplifyClientSide/>
          {children}
        </>
      </body>
    </html>
  )
}
